### ISSUE TITLE
Allow for project archival

### ISSUE THREAD

**Issue by ghost** [openknowledgebe/W4P#17]
Archival will work like this:

You link to the project's URL and the project's information is extracted from root/details.json. This information is saved in the current environment.

The "archived" snapshot should be visible in "previous projects" from then on.

**Comment by ghost** [comment]
Archived projects' meta property also contains a version number, so that we can correctly parse the meta information (mainly goals, total percentage, donors etc). 

If we ever want to change this (I imagine we can simplify this information in newer versions -- or perhaps new fields are added), we need to make sure the version number changes here as well.

![screen shot 2016-03-30 at 15 32 37](https://cloud.githubusercontent.com/assets/13518991/14143661/c0a48e38-f68c-11e5-8773-3000ce3d81af.png)

**Comment by ghost** [comment]
New migrations have been added. As usual, to run the migrations:

```
# new Doctrine/DBAL dependency was added
composer update
# dump autoloader
composer dump
# perform migrations
php artisan migrate
```

**Comment by ghost** [comment]
You can now import projects and they'll show up here:

![screen shot 2016-03-31 at 11 40 13](https://cloud.githubusercontent.com/assets/13518991/14171845/6142318a-f735-11e5-8e59-759abe0911c3.png)

Also useful for "other projects", but they won't show the accurate information. It would take no big effort to fetch the details.json and show the live stats from another installation should the need ever arise :)

**Comment by pietercolpaert** [comment]
A problem arises when doing this:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)



  [RuntimeException]                                                          
  Could not load package intervention/image in http://packagist.org: [Unexpe  
  ctedValueException] Could not parse version constraint 4.x.x: Invalid vers  
  ion string "4.x.x"                                                          






  [UnexpectedValueException]                                                
  Could not parse version constraint 4.x.x: Invalid version string "4.x.x"  



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]


$ php artisan migrate
PHP Fatal error:  Class 'Doctrine\DBAL\Driver\PDOSqlite\Driver' not found in /var/spitsgids/vendor/laravel/framework/src/Illuminate/Database/SQLiteConnection.php on line 49


  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Doctrine\DBAL\Driver\PDOSqlite\Driver' not found  

```

**Comment by pietercolpaert** [comment]
Solution was to run `composer self-update`: old version of composer broke things :)
