### ISSUE TITLE
No supported encrypter found

### ISSUE THREAD

**Issue by tthoeye** [openknowledgebe/W4P#18]
after following setup instructions and navigating to /public I get: No supported encrypter found. The cipher and / or key length are invalid.

![w4p](https://cloud.githubusercontent.com/assets/1484581/13507659/e0d48848-e183-11e5-8160-b24c0b707571.png)

Solution is to php artisan key:generate

Should be added to instructions

**Comment by ghost** [comment]
I've added this to the SETUP instructions file as a new step.

The setup script that already included this step, see https://github.com/openknowledgebe/W4P/blob/develop/vagrant/setup.sh#L121. But I totally forgot to add it to the SETUP file, so thanks.
