### ISSUE TITLE
No htaccess?

### ISSUE THREAD

**Issue by tthoeye** [openknowledgebe/W4P#19]
By default no .htaccess is included or generated, so URL rewrites don't work

**Comment by tthoeye** [comment]
I was wrong - its there. Only Apache 2.4 with mod_rewrite is being a bitch: http://stackoverflow.com/questions/17095981/why-apache-mod-rewrite-rewrites-twice-my-url?rq=1

**Comment by dive-michiel** [comment]
So, can close? :)
