### ISSUE TITLE
Page metadata

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#23]
I thing support for each page for: 
- [x] Twitter cards https://dev.twitter.com/cards/overview → should also include the video of the crowd-funding campaign when you include this URL in a tweet
- [x] Facebook open graph: https://developers.facebook.com/docs/sharing/best-practices
- [x] Google schema.org rich snippets: https://developers.google.com/structured-data/rich-snippets/products#about_product_offers
- [x] fill out the `<title></title>` tag properly: is now just "homepage"
- [x] fill out dcterms descriptions in meta tags - see also: http://stackoverflow.com/questions/23033027/dublin-core-html5-w3c-valiation-error

This is a strong requirement! Is the most basic SEO en SMO thing to do :)

**Comment by ghost** [comment]
@pietercolpaert: I would use [articles](https://developers.google.com/structured-data/rich-snippets/articles) for Google's schema.org rich snippets. There are no real reviews on the site, and what is being offered isn't necessarily a product. Is this okay?

Relevant meta properties correspond well to the kind of metadata we have (publisher, headline, etc)

**Comment by pietercolpaert** [comment]
@u-nico But it isn't an article... Maybe it's better to then describe the [video](https://developers.google.com/structured-data/rich-snippets/videos) instead?

**Comment by ghost** [comment]
Right now, unless specified, each page (view) uses the default meta tags (about the project) -- as can be found on the home page. I've added a partial for donation pages (/views/partials/meta/donate.blade.php) which can be _reused_ -- (and is already in use on w4p.dev/donate, for example) It's just placeholder comments, though.

What kind of meta tags would you like to see on the donate page? 

I can imagine that people will probably link to 1) the donate page (immediately) or 2) the homepage so this is a significant page and clearly the meta tags should differ from the ones on the homepage.

**Comment by pietercolpaert** [comment]
On the donate page I would try to find something that links as quick as possible to coming to the action of pressing that next button ;)

If product is not a good match, would still describe the video... WDYT?

**Comment by ghost** [comment]
Well, if that's the case we'll go with the default here as well; I've already made it so that the default describes the video.

**Comment by pietercolpaert** [comment]
Ok! And I also would prefer for the content of these fields configurability over making all these fields generic based on what you filled out in e.g., the description field. How your crowd-funder appears on social media is quite important :)

**Comment by ghost** [comment]
Sure. Should be no problem to add a "social media" page; after all, I need a place to put #30 as well. Makes a lot of sense to make many of these fields configurable. (After all, being able to tweak the platform is one of its major positive points.)

I'm guessing we'll need at least these:
- [x] Twitter handle
- [x] Twitter default share message (when sharing via widget)
- [x] Facebook page URL
- [x] Facebook default share message (when sharing via widget)
- [x] Default title for shared pages
- [x] Default description for shared pages

Feel free to let me know if I missed any important ones.

**Comment by pietercolpaert** [comment]
I guess also the standard image and/or video to show through twitter/facebook

**Comment by ghost** [comment]
Heading to **Administration > Manage > Social media settings** now allows you to customize the meta tags used on most pages. 

A few notes:
- The defaults are used if they are left empty. The defaults are the project title and project's brief description (this is the only place where the brief description is used by default).
- A Twitter handle is required before Twitter card meta tags are added.
- Twitter share message & FB share message are not ready yet (see #38).
- For the special pages and the posts left by the administrators, the pages'/posts' titles and descriptions are used.

**Comment by pietercolpaert** [comment]
`<title>` is still Homepage here...

**Comment by ghost** [comment]
My bad. Should be fixed with the latest commit.

**Comment by pietercolpaert** [comment]
It's still Homepage by default? Shouldn't it be the project name by default?

**Comment by ghost** [comment]
Good point. Maybe "(project name) • Home" is better as a default? Or is the project's name enough?

**Comment by pietercolpaert** [comment]
project name enough imo...

**Comment by ghost** [comment]
All right. I've changed it.

**Comment by pietercolpaert** [comment]
Thanks! Looks great! :)
