### ISSUE TITLE
How to change the © notice?

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#24]
Is this hard coded? Or can it be changed through configuration?

**Comment by ghost** [comment]
This was not possible before. I've changed default behaviour and added a custom option.

![screen shot 2016-03-14 at 11 54 21](https://cloud.githubusercontent.com/assets/13518991/13742364/b3ea3c82-e9db-11e5-95c2-a9724f5c9623.png)

Head over to Administration > Platform to adjust the copyright notice. If you leave the field empty, it will show:

© [YYYY], [organisation name]

If you set a custom notice, the entire field is replaced with your custom copyright notice.
