### ISSUE TITLE
Vimeo embed could be nicer

### ISSUE THREAD

**Issue by PieterJanPauwels** [openknowledgebe/W4P#32]
Cf. Screenshot below. 
Would make this as clean as possible: 
- Remove the Vimeo user logo
- Remove the Vimeo user name
- Remove the Vimeo video title

Optional: Remove the Watch later button
- Give the video the right proportions. Embed is now square while all modern videos have a 16:9 ratio.
  Vimeo adds ugly and unnecessary black strips to compensate. 

<img width="558" alt="screen shot 2016-03-15 at 11 01 39" src="https://cloud.githubusercontent.com/assets/6347860/13774130/94dc5a10-ea9d-11e5-83ff-e7e6ecfa8cf1.png">

**Comment by ghost** [comment]
@PieterJanPauwels: I agree, but removing controls and more needs to be done by the video's creator and requires Vimeo Plus/Pro. See: http://stackoverflow.com/a/24972198. Doing this with a hack used to be possible but that's against the TOS anyway.

Aspect ratio can be fixed.

**Comment by ghost** [comment]
(Title and byline can also be hidden. It's the actual controls that cannot be hidden unless you're a Plus/Pro user.)

**Comment by ghost** [comment]
Okay, should be fixed now. Aspect ratio has been fixed for both YouTube and Vimeo, and some of the extra information is now hidden on the embed.
