### ISSUE TITLE
Run migrations & seeding for existing installations

### ISSUE THREAD

**Issue by ghost** [openknowledgebe/W4P#36]
@pietercolpaert 
@tthoeye 

In order to allow for customizable pages (like the "How it works" page, or the "Terms of use" page) I've had to add a new table to the database and seed some default page names. 

After pulling from `develop`, you will need to run migrations and run the seeder:

EDIT: Also run `composer dump` first to update the autoloader's classes

```
php artisan migrate
php artisan db:seed
```

And you should be fine. You can go to **Administration > Manage > Manage pages** and pick the page you'd like to edit. The links in the footer are functional as well, so you should be able to visit those pages (they are empty by default, with the exception of the title, which are defaults).

**Comment by pietercolpaert** [comment]
Thanks for the heads up! Will pull our instances :)

**Comment by pietercolpaert** [comment]
Hmmm...

```
$php artisan db:seed


  [ReflectionException]                    
  Class DefaultPagesSeeder does not exist
```

Any idea about this error?

**Comment by ghost** [comment]
You should dump the autoloader first, probably.

```
composer dump
```

**Comment by pietercolpaert** [comment]
That did the trick!

**Comment by pietercolpaert** [comment]
Should I also compile something client-side? Don't see this manage pages link

**Comment by ghost** [comment]
I've made some small CSS changes as well, so it might be useful to run gulp again, but that shouldn't be the issue.

The four pages should be in the menu like this:

![screen shot 2016-03-16 at 14 10 43](https://cloud.githubusercontent.com/assets/13518991/13813264/e719dd50-eb80-11e5-8a3e-95095f6172e9.png)

**Comment by pietercolpaert** [comment]
My brain looked right over it. Thanks for the screenshot! Works ;-)

**Comment by ghost** [comment]
It might be useful for future reference to always run:

`composer dump && gulp` 

after pulling, just to make sure you've got all the latest changes. I'll also add this to the SETUP.md file.
