### ISSUE TITLE
Previous projects

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#37]
I'm running the first W4P project... Can I disable this button? :p

**Comment by ghost** [comment]
I'll make sure it disappears if you haven't archived a single project yet. #17 isn't done yet, so it's just an empty table for now -- so it'll always be hidden. But that's fine for now, I guess ;P

**Comment by pietercolpaert** [comment]
Thanks!

**Comment by ghost** [comment]
Once you've imported a ("previous") project, you can now see the button again :)
