### ISSUE TITLE
Organisation logo on FE instead of platform logo

### ISSUE THREAD

**Issue by Dobbelsteen** [openknowledgebe/W4P#40]
If an organisation logo is set, it should be displayed on the FE-side instead of the platform logo, no?
Currently it's not displayed anywhere.

Alternatively, use the organisation-logo in the facebook/twitter metatags as image

**Comment by ghost** [comment]
The original intention was to be able to add this logo below the organisation's details (next to About this project) but I'm not sure if that is still needed.

**Comment by Dobbelsteen** [comment]
It would be nice to have it visible in a prominent place, otherwise there's no point in having it. But that can be done along with the other styling :)

**Comment by ghost** [comment]
I'll close this and add it to #16 then :)
