### ISSUE TITLE
Goal progress % incorrect

### ISSUE THREAD

**Issue by Dobbelsteen** [openknowledgebe/W4P#41]
If you have a set amount of money as goal for a project, but there have been no money donations yet, the goal % is incorrect (it ignores the 0% of money donated).

Happens because in `DonationKind::getTotalPercentage($percentages, $currencyPercentage)`, there is a check if $currencyPercentage != null, however, if that percentage is currently 0, the application processes it as if it's null, making it ignore the money, even though it's part of the goal.

Small hack/fix: 
_HomeController_ at line 57

``` php
if ($project->currency > 0) {
    $contributedPercentage = round(($contributed / $project->currency) * 100, 1);

    if ($contributedPercentage > 100) {
        $currencyPercentage = 100;
    } else {
        $currencyPercentage = $contributedPercentage;
        // Start "awesome" hack
        // If percentage is 0, but project->currency > 0, make percentage a small number so that it isn't processed as null
        if($currencyPercentage == 0) {     
            $currencyPercentage = 0.01;
        }
        // End "awesome" hack
    }
} else {
    $currencyPercentage = null;
}
```

**Comment by ghost** [comment]
Thanks for the report (& fix), I'll make sure it's fixed when I work on project archival later today.

**Comment by Dobbelsteen** [comment]
(Y)
