### ISSUE TITLE
Images in the description section don't resize properly

### ISSUE THREAD

**Issue by PieterJanPauwels** [openknowledgebe/W4P#47]
Two examples:

The photo images gets cut off by the rewards tier windows. I resized the image to 850px (maximum width of the text). The other is a GIF showing how we use the data in this particular project, but it's cut off on mobile view. 

![screen shot 2016-04-07 at 13 52 59](https://cloud.githubusercontent.com/assets/6347860/14350204/35011d14-fcc8-11e5-8755-ad37ecaf5793.png)

![screen shot 2016-04-07 at 13 53 10](https://cloud.githubusercontent.com/assets/6347860/14350205/360eb310-fcc8-11e5-9866-a9c96faad820.png)

**Comment by ghost** [comment]
see #39

**Comment by ghost** [comment]
I'm closing this and reopening #39.

**Comment by ghost** [comment]
See also #16, styling isn't finished yet.
