### ISSUE TITLE
Tried to donate less money than the mollie cut from total to see what happens

### ISSUE THREAD

**Issue by wesobi** [openknowledgebe/W4P#57]
I tried to donate € 0.1 and €0.01 euro to see what would happens as I remember Mollie cuts a certain amount for transactions.

If you do this, the confirm page will give the standard Laravel error page with "Something went wrong".

**Steps to reproduce:**
- Go to "steun dit project"
- Donate custom amount less than X (what Mollie cuts?) f.e. €0.1
- Push submit
- get error page.

**Comment by ghost** [comment]
This is most likely a Mollie error. 

To avoid this, I'll raise the minimum limit to the lowest tier or at least €0.5, whichever is the highest.
