### ISSUE TITLE
Thank you e-mail gets in spam folder

### ISSUE THREAD

**Issue by Izoman** [openknowledgebe/W4P#61]
It shouldn't be seen as spam/junk e-mail.
Sender e-mail: info@spitsgids.be
![capture](https://cloud.githubusercontent.com/assets/13185885/14967432/b11a07f0-10b7-11e6-8297-10e5222dc535.PNG)

**Comment by pietercolpaert** [comment]
@tuinslak - this goes through your servers... Anything we can do about this?

**Comment by Tuinslak** [comment]
I don't know what client you use, but no, not much you can do about this. Although SPF & DKIM are probably not set up. 

If it's something like Gmail: get enough people to (not) mark it as spam
Any other client: make it look less spammy, less links, etc

http://kb.mailchimp.com/delivery/spam-filters/my-campaigns-are-going-to-spam-folders
http://mailchimp.com/resources/guides/how-to-avoid-spam-filters/html/
http://isnotspam.com/
