### ISSUE TITLE
Twitter share message gives the URL twice

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#62]
This is generated by the crowdfunder:

https://twitter.com/intent/tweet?url=https%3A%2F%2Fspitsgids.be&text=Nooit%20meer%20een%20te%20drukke%20trein%20met%20http%3A%2F%2Fspitsgids.be&original_referer=

**Comment by ghost** [comment]
Did you add the URL to the customized message yourself? This should happen by default.

**Comment by pietercolpaert** [comment]
Yes I did. Thanks, fixed :)
