### ISSUE TITLE
Can only see message when payment is acknowledged

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#64]
The only way to see the message of the user in the admin page is on the confirmation page, which does not yet exist when the payment wasn't accepted yet. For payments that take a while, this can be annoying though. Is there a way to show the message in another way?

**Comment by ghost** [comment]
I'll make an admin-specific version of the donation page that you can view even when the donation payment isn't done yet.

**Comment by ghost** [comment]
I've pushed a change. "Go to page" now always shows you the information as an admin, including the message. No more pesky -- "not confirmed yet" messages of any kind (at least not for admins).
