### ISSUE TITLE
Markdown preview not working

### ISSUE THREAD

**Issue by ghost** [openknowledgebe/W4P#70]
![screen shot 2016-05-09 at 11 12 26](https://cloud.githubusercontent.com/assets/13518991/15108571/ef6f91cc-15d6-11e6-8351-9e4eea9a76c3.png)

Markdown doesn't seem to parsed when hitting the preview button on my test environment. Any ideas why this can be, @wesobi?

**Comment by wesobi** [comment]
checking into it, though this should not be the case.

**Comment by wesobi** [comment]
The library seems to be reliant on other libraries (markdown.js or to-markdown.js) for the preview function. I added them but it did not seem to fix it simply by adding them so I'll check into it.
